In [1]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [2]:
from word2number import w2n
word_to_number=w2n.word_to_num("two million three thousand nine hundred and eighty four")
print(word_to_number)

2003984


In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df=pd.read_csv("homeprice.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
import math
mean_val=math.floor(df.bedrooms.mean())
df.bedrooms=df.bedrooms.fillna(mean_val)
df.bedrooms


0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [7]:
reg=linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [8]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

221323.00186540408

In [10]:
reg.predict([[3000,3,15]])

array([579201.19929613])

In [11]:
df=pd.DataFrame({
    "Experience":["One","Two","Three","Four"],
    "Salary":[1213,131,1311,131]
})
df

Experience  Salary
0        One    1213
1        Two     131
2      Three    1311
3       Four     131

In [13]:
df=pd.read_csv("homeprice2.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
df.experience=df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [18]:
mean_test_score=math.floor(df["test_score(out of 10)"].mean())
mean_test_score
df["test_score(out of 10)"]=df["test_score(out of 10)"].fillna(mean_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
df.experience=df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [20]:
reg=linear_model.LinearRegression()
reg.fit(df[["experience","test_score(out of 10)","interview_score(out of 10)"]],df["salary($)"])

LinearRegression()

In [21]:
reg.predict([[50,8,8]])

array([196056.4355254])